version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      runtime-dependencies:
        patterns:
          - fastapi
          - mcp
          - numpy
          - pydantic
          - safetensors
          - tokenizers
          - torch
          - transformers
          - uvicorn
      developer-dependencies:
        patterns:
          - mypy
          - pre-commit
          - pytest
          - ruff
          - setuptools
