"""Core types and math exports for the Aurora trace field."""

from aurora.core.config import BudgetConfig, FieldConfig, PredictorConfig, ReplayConfig
from aurora.core.math import Array, cosine_similarity, diag_gaussian_logpdf, entmax_bisect, entropy, weighted_mean
from aurora.core.types import (
    ActionName,
    Anchor,
    DecoderOutput,
    DecoderRequest,
    ExperienceFrame,
    InjectResult,
    MaintenanceStats,
    PosteriorGroup,
    PredictorPeek,
    PredictorState,
    ProposalDecision,
    ResponseResult,
    SourceType,
    SnapshotMeta,
    TraceEdge,
    TraceRecord,
    Workspace,
)

__all__ = [
    "ActionName",
    "Anchor",
    "Array",
    "BudgetConfig",
    "DecoderOutput",
    "DecoderRequest",
    "FieldConfig",
    "ExperienceFrame",
    "InjectResult",
    "MaintenanceStats",
    "PosteriorGroup",
    "PredictorConfig",
    "PredictorPeek",
    "PredictorState",
    "ProposalDecision",
    "ReplayConfig",
    "ResponseResult",
    "SnapshotMeta",
    "SourceType",
    "TraceEdge",
    "TraceRecord",
    "Workspace",
    "cosine_similarity",
    "diag_gaussian_logpdf",
    "entmax_bisect",
    "entropy",
    "weighted_mean",
]
